version: '3'
services:
  flask_app_1:
    build: ./dockerapp1
    ports:
      - "5001:5000"
    volumes:
      - ./dockerapp1:/app
  flask_app_2:
    build: ./dockerapp2
    ports:
      - "5002:5000"
    volumes:
      - ./dockerapp2:/app
